# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter

# This GitHub Actions workflow is designed to run several linters on the code base whenever changes are pushed
# to the main branch or a pull request is opened against the main branch. It can also be triggered manually
# using the workflow_dispatch event.
#
# The workflow consists of a single job named "run-lint" which performs the following steps:
# 1. Harden Runner: Uses the step-security/harden-runner action to enhance the security of the runner environment.
# 2. Checkout code: Uses the actions/checkout action to fetch the code from the repository with full git history.
# 3. Lint Code Base: Uses the super-linter/super-linter action to run various linters on the code base.
#
# The workflow requires the following permissions:
# - contents: write (for the workflow itself)
# - contents: read (for actions/checkout to fetch code)
# - statuses: write (for super-linter to mark the status of each linter run)
#
# Environment variables:
# - DEFAULT_BRANCH: Specifies the default branch (main) for the repository.
# - GITHUB_TOKEN: Provides a token to authenticate with GitHub.
# - DISABLE_ERRORS: Disables errors in the linter output (set to true).
#
# For more information on configuring and using the Super Linter, visit:
# https://github.com/github/super-linter

name: Lint Code Base

on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: write

concurrency:
  group: superlinter-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run-lint:
    permissions:
      contents: read # for actions/checkout to fetch code
      statuses: write # for github/super-linter to mark status of each linter run
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@502f4fe48a81a392756e173e39a861f8c8efe056 # v8.3.0
        #checkov:skip=skip-check:CKV2_GHA_1
        env:
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
          MARKDOWN_LINT_DISABLE: true
